version: '3'

services:
  database:
    container_name: 'container_db_graph'
    image: 'postgres:latest'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - container_api_database

  api:
    container_name: 'container_api'
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    networks:
      - container_api_database

networks:
  container_api_database:
    driver: bridge
